blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/muhittincamdali/iOS-Notification-Framework#readme
    about: Check out the documentation first
  - name: ðŸ’¬ Discussions
    url: https://github.com/muhittincamdali/iOS-Notification-Framework/discussions
    about: Ask questions and discuss ideas
